
export const RECEIVED_STREAM_DATA = "RECEIVED_STREAM_DATA";
export const FETCH_STREAM_DATA = "FETCH_STREAM_DATA";
export const SHOW_REVIEW_EDITOR = "SHOW_REVIEW_EDITOR";
export const REVIEW_EDITOR_ALBUM_INPUT_CHANGED = "REVIEW_EDITOR_ALBUM_INPUT_CHANGED";
export const REVIEW_EDITOR_ALBUM_SUGGESTIONS_REQUESTED = "REVIEW_EDITOR_ALBUM_SUGGESTIONS_REQUESTED";
export const REVIEW_EDITOR_RECEIVED_ALBUM_SUGGESTIONS = "REVIEW_EDITOR_RECEIVED_ALBUM_SUGGESTIONS";
export const REVIEW_EDITOR_ALBUM_SELECTED = "REVIEW_EDITOR_ALBUM_SELECTED";
export const CLEAR_ALBUM_SUGGESTIONS = "CLEAR_ALBUM_SUGGESTIONS";
